services:

  frontend:
    build: ./frontend
    ports:
      - "9090:80"

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
